[project]
name = "rishta-agent-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.28.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "dotenv>=0.9.9",
    "openai-agents>=0.2.2",
]
